name: adf-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          sqlsourceUserId: ${{ secrets.sqlsourceUserId }}
          sqlsourcePassword: ${{ secrets.sqlsourcePassword }}
          sqlsinkUserId: ${{ secrets.sqlsinkUserId }}
          sqlsinkPassword: ${{ secrets.sqlsinkPassword }}    

      # Deploy ARM template
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: East US
          resourceGroupName: ${{ secrets.RESOURCE_GROUP}}
          template: Datafactory/template/restapi.bicep
